### ISSUE TITLE
New circom exercise

### ISSUE THREAD

**Issue by extropyCoder** [ExtropyIO/ZeroKnowledgeBootcamp#25]
Replace circom exercise exrx-mult with a new exercise requiring roughly 6 lines of code to complete
The exercise will need to be ready for today's lesson, so judge the work accordingly

**Comment by foxreymann** [comment]
https://github.com/ExtropyIO/CircomExrx/pull/1

**Comment by foxreymann** [comment]
https://github.com/ExtropyIO/ZeroKnowledgeBootcamp/pull/26
